### ISSUE TITLE
Items sometimes being moved to inventories when opening them

### ISSUE THREAD

**Issue by UpcraftLP** [gbuimc/MouseTweaksForRift#2]
When opening an inventory on a multiplayer (vanilla) server, sometimes items move to that inventory automatically.
This seems to only occur if there is an item in an inventory slot that#s rendered in the center of the screen, i.e. where the mouse is held while no GUI is open.

mc: 1.13
version: 0.1.2
rift: 1.0.2-33

**Comment by gbui** [comment]
I think I know why this is happening... Thanks for the report!
