### ISSUE TITLE
Mouse Tweaks simply not working (MultiMC incompatibility?)

### ISSUE THREAD

**Issue by DefinitelyNotFred** [gbuimc/MouseTweaksForRift#3]
Mouse Tweaks isn't working for me: no shortcuts are working and no config file has been generated. Other Rift mods are working just fine. I'm using MultiMC 0.6.2-1222. It shows in the log that it was recognized but there doesn't seem to be anything else about it in there - no relevant errors or warnings. Here's my log: https://pastebin.com/FEiWHvtb

**Comment by gbui** [comment]
`MouseTweaks-2.8-mc1.12.1` 😜

**Comment by DefinitelyNotFred** [comment]
Oh, is it for 1.12 only? All the curse forge files say they are for 1.13.

**Comment by gbui** [comment]
No, you have the wrong version installed. Here you go: https://minecraft.curseforge.com/projects/mouse-tweaks-for-rift/files/2603439

**Comment by DefinitelyNotFred** [comment]
Huh, I must have accidently downloaded it from the non-rift version when I was looking at the shortcuts guide. Sorry for the trouble.
